apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  mysql_root_password: UEBzc1cwckQ=
  mysql_password: TXlTUUwxMjM=
  wordpress_db_password: TXlTUUwxMjM=